# 2.8 数组的排序

np.sort 就地排序数组

np.argsort 返回的是原始数组排序好的索引值

np的排序算法的一个有用的功能是通过axis参数，沿着多维数组的行或者列进行排序



In [1]:
import numpy as np

x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [2]:
# 上面的索引数组可以用于fancy-index

print(x[i])

[1 2 3 4 5]


In [3]:
rand = np.random.RandomState(42)

X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [4]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [5]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## 2.8.2 部分排序: 分隔

np.partition, 将数组分隔为两个区间，两个元素都是任意排列的，只保证左边的满足第k小。

In [6]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [7]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])