# NumPy 数组基础

## 数组的属性

```

x3 ndim:  3               数组的维度
x3 shape: (3, 4, 5)       数组每个维度的大小
x3 size:  60              数组的总大小
x3 dtype: int32           数组的数据类型

itemsize: 4 bytes         单个元素的字节数
nbytes: 240 bytes         数组的总字节数

```


In [1]:
import numpy as np

np.random.seed(0)  # 设置随机种子

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))


In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype:", x3.dtype)

print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## 数组的索引

一维数组中，通过`[]` 获取第i个值

二维数组通过 `[x,y]` 访问某个元素，也可以对其赋值来修改该元素


In [3]:
print(x1)

var1 = x1[0]

x1[4]


[5 0 3 3 7 9]


7

In [4]:
print(x2)

print(x2[0, 0])
print(x2[2, 0])

print(x2[-1, -1])

# x2[0, 0] = 12

# print(x2[1])

x2[1]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
1
7


array([7, 6, 8, 8])

## 数组的切片

slice : `x[start:stop:step]`

如果以上3个参数都未指定，那么它们会被设置为默认值 start=0, stop=维度的大小(size of dimension)和step=1

数组切片返回的是数组数据的视图，而不是数值数据的副本。如果修改子数组，原始的数组也会被修改。

在处理非常大的数据集时，可以获取或处理这些数据集的片段，而不用复制底层的数据缓存。

-------

创建数组的副本，可以显式的使用 `copy()` 方法


1. 一维子数组

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 前五个元素
x[:5]

array([0, 1, 2, 3, 4])

In [7]:
x[4:7]

array([4, 5, 6])

In [8]:
x[::2]

array([0, 2, 4, 6, 8])

In [9]:
# 每隔一个元素，从索引1开始
x[1::2]

array([1, 3, 5, 7, 9])

In [10]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
"""
当步长step为负值时， start 和 stop 参数默认是被交换的
所以如下的表达式 [5::-2] -> [5:0:-2] -> [0:5:2]

"""

x[5::-2]

array([5, 3, 1])

2. 多维子数组

多维切片也采用同样的方式处理，用逗号分隔


In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
"""
在每个维度上操作:

:2 -> 0:2:1
:3 -> 0:3:1

"""

x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [14]:
x2[:2, ]

array([[3, 5, 2, 4],
       [7, 6, 8, 8]])

In [15]:
# 等价于
# x2[:3, 0:4:2]

x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [16]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

3. 获取数组的行和列

获取数组的单行和单列，可以将索引和切片组合起来实现这个功能，用一个冒号表示空切片

In [17]:
x2[:, 0] # x2的第一列

array([3, 7, 1])

In [18]:
x2[0, :] # x2的第一行

array([3, 5, 2, 4])

In [20]:
# 在获取行时，处于语法的简洁，可以省略空的切片

x2[0]

array([3, 5, 2, 4])

In [21]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

In [22]:
x2_sub[0, 0] = 99

x2 # 原始数组也被更改了

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [23]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [24]:
x2_sub_copy[0, 0] = 4

x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])