# 通用函数

使Numpy变快的关键是利用向量化操作，通常在Numpy的通用函数ufunc中实现



In [1]:
import numpy as np

## 常见的通用函数

分为一元通用函数 unary ufunc 和 二元通用函数 binary ufunc

一元通用函数之间可以任意组合使用。所有的算术运算都是numpy内置函数的封装，例如+就是 add 函数的封装。

| Operator | Equivalent ufunc    | Description                             |
|----------|---------------------|-----------------------------------------|
| ``+``    | ``np.add``          | Addition (e.g., ``1 + 1 = 2``)          |
| ``-``    | ``np.subtract``     | Subtraction (e.g., ``3 - 2 = 1``)       |
| ``-``    | ``np.negative``     | Unary negation (e.g., ``-2``)           |
| ``*``    | ``np.multiply``     | Multiplication (e.g., ``2 * 3 = 6``)    |
| ``/``    | ``np.divide``       | Division (e.g., ``3 / 2 = 1.5``)        |
| ``//``   | ``np.floor_divide`` | Floor division (e.g., ``3 // 2 = 1``)   |
| ``**``   | ``np.power``        | Exponentiation (e.g., ``2 ** 3 = 8``)   |
| ``%``    | ``np.mod``          | Modulus/remainder (e.g., ``9 % 4 = 1``) |

**绝对值**

python内置的 `abs`

Numpy中的 `np.absolute` `np.abs`, 也可以处理复数，返回复数的模 (magnitude)

**三角函数 Trigonometric functions**

**指数和对数**

Exponents and logarithms


**专用的通用函数**

来源是 `scipy.special` gamma function python


In [2]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)



x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [3]:
np.add(x, 2)

array([2, 3, 4, 5])

In [4]:
theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
print()

# 逆三角函数
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [5]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [6]:
from scipy import special

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]
erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


## 高级的通用函数特性

1. 指定输出
所有的通用函数通过out参数来指定计算结果的存放位置

2. 聚合
可以用任何通用函数的reduce方法，对给定的元素和操作重复执行，直到得到单个的结果

3. 外积
任何通用函数都可以用outer方法获得两个不同输入数组所有元素对函数运算结果


In [7]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

y1 = np.zeros(10)
np.power(2, x, out=y1[::2])
print(y1)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [8]:
x = np.arange(1, 6)
print(np.add.reduce(x))

# 存储每次计算的中间结果
print(np.add.accumulate(x))

15
[ 1  3  6 10 15]


In [9]:
x = np.arange(1, 6)
np.multiply.outer(x, x)
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])