# 数组的计算: 广播

如何通过通用函数的向量化操作来减少缓慢的Python循环

另外一种向量化操作的方法是利用numpy的广播功能。

广播可以简单理解为用于不同大小数组的二元通用函数的一组规则。

## 介绍

对于同样大小的数组，二元运算符是对相应元素逐个计算。

![Broadcasting Visual](figures/02.05-broadcasting.png)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([5, 5, 5])

print(a + b)

[6 7 8]


In [2]:
"""
一个标量(可以认为是零维数组)和一个数组相加: a + 5 

将数值5扩展至 [5,5,5] 然后执行加法
"""

print(a + 5)

[6 7 8]


In [3]:
"""
这里这个一维数组就被扩展了，它沿着第二个维度扩展，扩展到匹配M数组的形状


"""

M = np.ones((2, 3))

print(M)
print(a)

print(f'M shape: {M.shape}')
print(f'a shape: {a.shape}')

print(M + a)

[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]
M shape: (2, 3)
a shape: (3,)
[[2. 3. 4.]
 [2. 3. 4.]]


In [4]:
"""
这里a和b都会进行扩展。

a -> (x, 3) -> (3, 3)
b -> (3, 1) -> (3, 3)

"""

a = np.arange(3)

b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

print(f'a shape: {a.shape}')
print(f'b shape: {b.shape}')

print(a + b)

[0 1 2]
[[0]
 [1]
 [2]]
a shape: (3,)
b shape: (3, 1)
[[0 1 2]
 [1 2 3]
 [2 3 4]]
