# Numpy QuickStart

An array axis(轴) and shape(形状) ???

dimensions are called axes.

- ndarray.ndim
- ndarray.shape
- ndarray.size
- ndarray.dtype
- ndarray.itemsize
- ndarray.data

`set_printoptions` 来控制print选项

-----------------

在numpy中

矩阵乘法用 `@` 或者 `A.dot(B)`

elementwise product 用 `*`


`np.fromfunction()`


In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
import sys

# 2**63 - 1
sys.maxsize

9223372036854775807

## Basic Operations

许多一元操作，例如计算数组中所有元素的和，都是作为ndarray类的方法实现的。

默认情况下，这些操作应用于数组，就像它是一个数字列表一样，不管它的形状如何。然而，通过指定axis参数，你可以沿着数组的指定轴应用一个操作:



In [3]:
a = np.random.random((2, 3))

print(a)

print(a.min())
print(a.max())

[[0.26251726 0.46791961 0.39732902]
 [0.57624765 0.46338571 0.61289694]]
0.26251726213227355
0.6128969350619162


In [4]:
b = np.arange(12).reshape(3, 4)

print(b)

print(b.sum(axis=0))

print(b.min(axis=1))

print(b.cumsum(axis=1))
print(b.cumsum(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


## 数组变形

reshape 返回新的数组, 如果在reshape操作中给定一个维度为-1，则自动计算其他维度

resize 原地修改数组

**数组的合并**

```
column_stack
vstack
hstack
row_stack
concatenate

```


In [5]:
a = np.floor(10 * np.random.random((3, 4)))

print(a)

print(a.shape)


[[9. 7. 4. 6.]
 [4. 3. 7. 7.]
 [1. 7. 2. 1.]]
(3, 4)


In [6]:
# 返回平面化的数组
print(a.ravel())

# 修改数组的维度
print(a.reshape(6, 2))

# 返回转置后的数组
print(a.T)

[9. 7. 4. 6. 4. 3. 7. 7. 1. 7. 2. 1.]
[[9. 7.]
 [4. 6.]
 [4. 3.]
 [7. 7.]
 [1. 7.]
 [2. 1.]]
[[9. 4. 1.]
 [7. 3. 7.]
 [4. 7. 2.]
 [6. 7. 1.]]


In [7]:

#
a.resize((2, 6))
print(a)

[[9. 7. 4. 6. 4. 3.]
 [7. 7. 1. 7. 2. 1.]]


## 数组的copy

有如下三种形式

- 赋值
- View or Shallow Copy
- deep copy
